# Generated by Django 5.2.15 on 2026-07-07 06:50

import apps.organization.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


def carry_config_into_global(apps, schema_editor):
    """Create the GlobalSchedule singleton, carrying grace/workdays from any
    existing AttendanceConfig (the Phase 1 per-employee schedule) as the default.
    Times default to 08:00/12:00/13:00/17:00 (no direct old equivalent)."""
    GlobalSchedule = apps.get_model('organization', 'GlobalSchedule')
    AttendanceConfig = apps.get_model('organization', 'AttendanceConfig')

    sample = AttendanceConfig.objects.first()
    GlobalSchedule.objects.update_or_create(
        pk=1,
        defaults={
            'am_in': datetime.time(8, 0), 'am_out': datetime.time(12, 0),
            'pm_in': datetime.time(13, 0), 'pm_out': datetime.time(17, 0),
            'grace_period_minutes': sample.grace_period_minutes if sample else 5,
            'workdays': (sample.workdays if sample and sample.workdays else [0, 1, 2, 3, 4]),
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('am_in', models.TimeField(default=datetime.time(8, 0))),
                ('am_out', models.TimeField(default=datetime.time(12, 0))),
                ('pm_in', models.TimeField(default=datetime.time(13, 0))),
                ('pm_out', models.TimeField(default=datetime.time(17, 0))),
                ('grace_period_minutes', models.PositiveIntegerField(default=5)),
                ('workdays', models.JSONField(default=apps.organization.models.default_workdays)),
            ],
            options={
                'verbose_name': 'Global Schedule',
                'verbose_name_plural': 'Global Schedule',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='is_fulltime',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('am_in', models.TimeField(blank=True, null=True)),
                ('am_out', models.TimeField(blank=True, null=True)),
                ('pm_in', models.TimeField(blank=True, null=True)),
                ('pm_out', models.TimeField(blank=True, null=True)),
                ('grace_period_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('workdays', models.JSONField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_override', to='organization.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        # Carry legacy AttendanceConfig data into the GlobalSchedule default
        # BEFORE dropping the old model.
        migrations.RunPython(carry_config_into_global, noop_reverse),
        migrations.DeleteModel(
            name='AttendanceConfig',
        ),
    ]
