# Generated by Django 5.2.15 on 2026-07-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_globalschedule_employee_is_fulltime_employeeschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
