# Generated by Django 5.2.15 on 2026-07-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='departments/banners/'),
        ),
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='departments/logos/'),
        ),
    ]
