# Generated by Django 5.2.15 on 2026-07-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_department_banner_department_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='color',
            field=models.CharField(default='#DC2626', max_length=7),
        ),
    ]
