# Generated by Django 5.2.17 on 2026-09-21 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_holiday_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='midpoint',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalschedule',
            name='midpoint',
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
    ]
