# Generated by Django 5.2.15 on 2026-10-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_schedule_midpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_seconds', models.FloatField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_ok', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Time Sync',
                'verbose_name_plural': 'Time Sync',
            },
        ),
    ]
