# Generated by Django 5.2.15 on 2026-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
    ]
