# Generated by Django 5.2.15 on 2026-07-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_datetime', models.DateTimeField()),
                ('log_type', models.CharField(choices=[('IN', 'Time In'), ('OUT', 'Time Out')], max_length=8)),
                ('raw_status', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('DEVICE', 'Biometric Device'), ('MANUAL', 'Manual Entry')], default='DEVICE', max_length=16)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='devices.biometricdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='organization.employee')),
            ],
            options={
                'ordering': ['-log_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Lates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('minutes_late', models.PositiveIntegerField()),
                ('attendance_log', models.ForeignKey(help_text='The IN log that triggered this lateness record.', on_delete=django.db.models.deletion.CASCADE, related_name='lateness', to='attendance.attendancelog')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lates', to='organization.employee')),
            ],
            options={
                'verbose_name_plural': 'Lates',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'log_datetime'], name='attendance__employe_a36f44_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(fields=('employee', 'log_datetime', 'log_type'), name='uniq_employee_logdt_logtype'),
        ),
        migrations.AddConstraint(
            model_name='lates',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_employee_late_date'),
        ),
    ]
