# Generated by Django 5.2.15 on 2026-07-07 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_derived(apps, schema_editor):
    """Lates/Absence are 100% derived and their rules changed this phase — clear
    them so process_day recomputes cleanly (no stale single-punch rows)."""
    apps.get_model('attendance', 'Lates').objects.all().delete()
    apps.get_model('attendance', 'Absence').objects.all().delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_absence'),
        ('organization', '0002_globalschedule_employee_is_fulltime_employeeschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_derived, noop_reverse),
        migrations.CreateModel(
            name='OTAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('ot_start', models.TimeField(help_text='Overtime counts from this time.')),
                ('ot_end_expected', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'OT authorization',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='absence',
            name='uniq_employee_absence_date',
        ),
        migrations.RemoveConstraint(
            model_name='lates',
            name='uniq_employee_late_date',
        ),
        migrations.AddField(
            model_name='absence',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absence',
            name='session',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('FULL', 'Full day')], default='FULL', max_length=4),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lates',
            name='session',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('FULL', 'Full day')], default='AM', max_length=4),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.CharField(choices=[('NO_PUNCH', 'No punch recorded'), ('MISSING_IN', 'Missing time in'), ('MISSING_OUT', 'Missing time out')], default='NO_PUNCH', max_length=16),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='log_type',
            field=models.CharField(choices=[('AM_IN', 'AM In'), ('AM_OUT', 'AM Out'), ('PM_IN', 'PM In'), ('PM_OUT', 'PM Out'), ('OT_IN', 'OT In'), ('OT_OUT', 'OT Out'), ('IN', 'Time In'), ('OUT', 'Time Out')], max_length=8),
        ),
        migrations.AlterField(
            model_name='lates',
            name='attendance_log',
            field=models.ForeignKey(help_text="The session's IN log that triggered this record.", on_delete=django.db.models.deletion.CASCADE, related_name='lateness', to='attendance.attendancelog'),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'session'), name='uniq_employee_absence_date_session'),
        ),
        migrations.AddConstraint(
            model_name='lates',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'session'), name='uniq_employee_late_date_session'),
        ),
        migrations.AddField(
            model_name='otauthorization',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otauthorization',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_authorizations', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='authorization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='attendance.otauthorization'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='organization.employee'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='ot_in_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_in_for', to='attendance.attendancelog'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='ot_out_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ot_out_for', to='attendance.attendancelog'),
        ),
        migrations.AddConstraint(
            model_name='otauthorization',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_ot_auth_employee_date'),
        ),
        migrations.AddConstraint(
            model_name='overtime',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uniq_overtime_employee_date'),
        ),
    ]
