# Generated by Django 5.2.15 on 2026-07-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_otauthorization_overtime_and_more'),
        ('organization', '0005_holiday_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Undertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('FULL', 'Full day')], default='AM', max_length=4)),
                ('minutes_undertime', models.PositiveIntegerField()),
                ('attendance_log', models.ForeignKey(help_text="The session's OUT log that triggered this record.", on_delete=django.db.models.deletion.CASCADE, related_name='undertime', to='attendance.attendancelog')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undertimes', to='organization.employee')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date', 'session'), name='uniq_employee_undertime_date_session')],
            },
        ),
    ]
