# Generated by Django 5.2.17 on 2026-09-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_undertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='source',
            field=models.CharField(choices=[('DEVICE', 'Biometric Device'), ('MANUAL', 'Manual Entry'), ('DEMO', 'Demo Data')], default='DEVICE', max_length=16),
        ),
    ]
