# Generated by Django 5.2.17 on 2026-09-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('DAILY_ATTENDANCE', 'Daily Attendance'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('TARDINESS', 'Tardiness'), ('ABSENCE', 'Absence'), ('EMPLOYEE_ATTENDANCE', 'Employee Attendance (DTR)')], max_length=32),
        ),
    ]
