# Generated by Django 5.2.15 on 2026-10-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportjob_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('DAILY_ATTENDANCE', 'Daily Attendance'), ('MONTHLY_SUMMARY', 'Monthly Summary'), ('TARDINESS', 'Tardiness'), ('ABSENCE', 'Absence'), ('EMPLOYEE_ATTENDANCE', 'Employee Attendance (DTR)')], max_length=32),
        ),
    ]
