# Generated by Django 5.2.15 on 2026-10-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_attendance_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='report_type',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('TARDINESS', 'Tardiness'), ('ABSENCE', 'Absence')], max_length=32),
        ),
    ]
