# Generated by Django 5.2.15 on 2026-07-06 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('LATE', 'Late'), ('ABSENCE', 'Absence'), ('GENERAL', 'General')], default='GENERAL', max_length=16)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organization.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
