# Generated by Django 5.2.15 on 2026-07-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_otauthorization_overtime_and_more'),
        ('notifications', '0001_initial'),
        ('organization', '0002_globalschedule_employee_is_fulltime_employeeschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='attendance_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='attendance.attendancelog'),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=8),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PUNCH', 'Punch'), ('ATTENDANCE', 'Attendance'), ('LATE', 'Late'), ('ABSENCE', 'Absence'), ('GENERAL', 'General')], default='GENERAL', max_length=16),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'sent_at'], name='notificatio_status_ed3675_idx'),
        ),
    ]
